# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mark/Programming/LP_hazi/Virtual-Sampler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mark/Programming/LP_hazi/Virtual-Sampler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mark/Programming/LP_hazi/Virtual-Sampler/CMakeFiles /home/mark/Programming/LP_hazi/Virtual-Sampler//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mark/Programming/LP_hazi/Virtual-Sampler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Virtual-Sampler

# Build rule for target.
Virtual-Sampler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Virtual-Sampler
.PHONY : Virtual-Sampler

# fast build rule for target.
Virtual-Sampler/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Virtual-Sampler.dir/build.make CMakeFiles/Virtual-Sampler.dir/build
.PHONY : Virtual-Sampler/fast

libs/miniaudio/miniaudio.o: libs/miniaudio/miniaudio.c.o
.PHONY : libs/miniaudio/miniaudio.o

# target to build an object file
libs/miniaudio/miniaudio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Virtual-Sampler.dir/build.make CMakeFiles/Virtual-Sampler.dir/libs/miniaudio/miniaudio.c.o
.PHONY : libs/miniaudio/miniaudio.c.o

libs/miniaudio/miniaudio.i: libs/miniaudio/miniaudio.c.i
.PHONY : libs/miniaudio/miniaudio.i

# target to preprocess a source file
libs/miniaudio/miniaudio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Virtual-Sampler.dir/build.make CMakeFiles/Virtual-Sampler.dir/libs/miniaudio/miniaudio.c.i
.PHONY : libs/miniaudio/miniaudio.c.i

libs/miniaudio/miniaudio.s: libs/miniaudio/miniaudio.c.s
.PHONY : libs/miniaudio/miniaudio.s

# target to generate assembly for a file
libs/miniaudio/miniaudio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Virtual-Sampler.dir/build.make CMakeFiles/Virtual-Sampler.dir/libs/miniaudio/miniaudio.c.s
.PHONY : libs/miniaudio/miniaudio.c.s

source/app.o: source/app.cpp.o
.PHONY : source/app.o

# target to build an object file
source/app.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Virtual-Sampler.dir/build.make CMakeFiles/Virtual-Sampler.dir/source/app.cpp.o
.PHONY : source/app.cpp.o

source/app.i: source/app.cpp.i
.PHONY : source/app.i

# target to preprocess a source file
source/app.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Virtual-Sampler.dir/build.make CMakeFiles/Virtual-Sampler.dir/source/app.cpp.i
.PHONY : source/app.cpp.i

source/app.s: source/app.cpp.s
.PHONY : source/app.s

# target to generate assembly for a file
source/app.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Virtual-Sampler.dir/build.make CMakeFiles/Virtual-Sampler.dir/source/app.cpp.s
.PHONY : source/app.cpp.s

source/base.o: source/base.cpp.o
.PHONY : source/base.o

# target to build an object file
source/base.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Virtual-Sampler.dir/build.make CMakeFiles/Virtual-Sampler.dir/source/base.cpp.o
.PHONY : source/base.cpp.o

source/base.i: source/base.cpp.i
.PHONY : source/base.i

# target to preprocess a source file
source/base.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Virtual-Sampler.dir/build.make CMakeFiles/Virtual-Sampler.dir/source/base.cpp.i
.PHONY : source/base.cpp.i

source/base.s: source/base.cpp.s
.PHONY : source/base.s

# target to generate assembly for a file
source/base.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Virtual-Sampler.dir/build.make CMakeFiles/Virtual-Sampler.dir/source/base.cpp.s
.PHONY : source/base.cpp.s

source/filemanager.o: source/filemanager.cpp.o
.PHONY : source/filemanager.o

# target to build an object file
source/filemanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Virtual-Sampler.dir/build.make CMakeFiles/Virtual-Sampler.dir/source/filemanager.cpp.o
.PHONY : source/filemanager.cpp.o

source/filemanager.i: source/filemanager.cpp.i
.PHONY : source/filemanager.i

# target to preprocess a source file
source/filemanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Virtual-Sampler.dir/build.make CMakeFiles/Virtual-Sampler.dir/source/filemanager.cpp.i
.PHONY : source/filemanager.cpp.i

source/filemanager.s: source/filemanager.cpp.s
.PHONY : source/filemanager.s

# target to generate assembly for a file
source/filemanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Virtual-Sampler.dir/build.make CMakeFiles/Virtual-Sampler.dir/source/filemanager.cpp.s
.PHONY : source/filemanager.cpp.s

source/key.o: source/key.cpp.o
.PHONY : source/key.o

# target to build an object file
source/key.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Virtual-Sampler.dir/build.make CMakeFiles/Virtual-Sampler.dir/source/key.cpp.o
.PHONY : source/key.cpp.o

source/key.i: source/key.cpp.i
.PHONY : source/key.i

# target to preprocess a source file
source/key.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Virtual-Sampler.dir/build.make CMakeFiles/Virtual-Sampler.dir/source/key.cpp.i
.PHONY : source/key.cpp.i

source/key.s: source/key.cpp.s
.PHONY : source/key.s

# target to generate assembly for a file
source/key.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Virtual-Sampler.dir/build.make CMakeFiles/Virtual-Sampler.dir/source/key.cpp.s
.PHONY : source/key.cpp.s

source/keyhandler.o: source/keyhandler.cpp.o
.PHONY : source/keyhandler.o

# target to build an object file
source/keyhandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Virtual-Sampler.dir/build.make CMakeFiles/Virtual-Sampler.dir/source/keyhandler.cpp.o
.PHONY : source/keyhandler.cpp.o

source/keyhandler.i: source/keyhandler.cpp.i
.PHONY : source/keyhandler.i

# target to preprocess a source file
source/keyhandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Virtual-Sampler.dir/build.make CMakeFiles/Virtual-Sampler.dir/source/keyhandler.cpp.i
.PHONY : source/keyhandler.cpp.i

source/keyhandler.s: source/keyhandler.cpp.s
.PHONY : source/keyhandler.s

# target to generate assembly for a file
source/keyhandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Virtual-Sampler.dir/build.make CMakeFiles/Virtual-Sampler.dir/source/keyhandler.cpp.s
.PHONY : source/keyhandler.cpp.s

source/menubar.o: source/menubar.cpp.o
.PHONY : source/menubar.o

# target to build an object file
source/menubar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Virtual-Sampler.dir/build.make CMakeFiles/Virtual-Sampler.dir/source/menubar.cpp.o
.PHONY : source/menubar.cpp.o

source/menubar.i: source/menubar.cpp.i
.PHONY : source/menubar.i

# target to preprocess a source file
source/menubar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Virtual-Sampler.dir/build.make CMakeFiles/Virtual-Sampler.dir/source/menubar.cpp.i
.PHONY : source/menubar.cpp.i

source/menubar.s: source/menubar.cpp.s
.PHONY : source/menubar.s

# target to generate assembly for a file
source/menubar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Virtual-Sampler.dir/build.make CMakeFiles/Virtual-Sampler.dir/source/menubar.cpp.s
.PHONY : source/menubar.cpp.s

source/messages.o: source/messages.cpp.o
.PHONY : source/messages.o

# target to build an object file
source/messages.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Virtual-Sampler.dir/build.make CMakeFiles/Virtual-Sampler.dir/source/messages.cpp.o
.PHONY : source/messages.cpp.o

source/messages.i: source/messages.cpp.i
.PHONY : source/messages.i

# target to preprocess a source file
source/messages.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Virtual-Sampler.dir/build.make CMakeFiles/Virtual-Sampler.dir/source/messages.cpp.i
.PHONY : source/messages.cpp.i

source/messages.s: source/messages.cpp.s
.PHONY : source/messages.s

# target to generate assembly for a file
source/messages.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Virtual-Sampler.dir/build.make CMakeFiles/Virtual-Sampler.dir/source/messages.cpp.s
.PHONY : source/messages.cpp.s

source/namedialog.o: source/namedialog.cpp.o
.PHONY : source/namedialog.o

# target to build an object file
source/namedialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Virtual-Sampler.dir/build.make CMakeFiles/Virtual-Sampler.dir/source/namedialog.cpp.o
.PHONY : source/namedialog.cpp.o

source/namedialog.i: source/namedialog.cpp.i
.PHONY : source/namedialog.i

# target to preprocess a source file
source/namedialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Virtual-Sampler.dir/build.make CMakeFiles/Virtual-Sampler.dir/source/namedialog.cpp.i
.PHONY : source/namedialog.cpp.i

source/namedialog.s: source/namedialog.cpp.s
.PHONY : source/namedialog.s

# target to generate assembly for a file
source/namedialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Virtual-Sampler.dir/build.make CMakeFiles/Virtual-Sampler.dir/source/namedialog.cpp.s
.PHONY : source/namedialog.cpp.s

source/sliderhandler.o: source/sliderhandler.cpp.o
.PHONY : source/sliderhandler.o

# target to build an object file
source/sliderhandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Virtual-Sampler.dir/build.make CMakeFiles/Virtual-Sampler.dir/source/sliderhandler.cpp.o
.PHONY : source/sliderhandler.cpp.o

source/sliderhandler.i: source/sliderhandler.cpp.i
.PHONY : source/sliderhandler.i

# target to preprocess a source file
source/sliderhandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Virtual-Sampler.dir/build.make CMakeFiles/Virtual-Sampler.dir/source/sliderhandler.cpp.i
.PHONY : source/sliderhandler.cpp.i

source/sliderhandler.s: source/sliderhandler.cpp.s
.PHONY : source/sliderhandler.s

# target to generate assembly for a file
source/sliderhandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Virtual-Sampler.dir/build.make CMakeFiles/Virtual-Sampler.dir/source/sliderhandler.cpp.s
.PHONY : source/sliderhandler.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Virtual-Sampler"
	@echo "... libs/miniaudio/miniaudio.o"
	@echo "... libs/miniaudio/miniaudio.i"
	@echo "... libs/miniaudio/miniaudio.s"
	@echo "... source/app.o"
	@echo "... source/app.i"
	@echo "... source/app.s"
	@echo "... source/base.o"
	@echo "... source/base.i"
	@echo "... source/base.s"
	@echo "... source/filemanager.o"
	@echo "... source/filemanager.i"
	@echo "... source/filemanager.s"
	@echo "... source/key.o"
	@echo "... source/key.i"
	@echo "... source/key.s"
	@echo "... source/keyhandler.o"
	@echo "... source/keyhandler.i"
	@echo "... source/keyhandler.s"
	@echo "... source/menubar.o"
	@echo "... source/menubar.i"
	@echo "... source/menubar.s"
	@echo "... source/messages.o"
	@echo "... source/messages.i"
	@echo "... source/messages.s"
	@echo "... source/namedialog.o"
	@echo "... source/namedialog.i"
	@echo "... source/namedialog.s"
	@echo "... source/sliderhandler.o"
	@echo "... source/sliderhandler.i"
	@echo "... source/sliderhandler.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

